Repository canonical/jp.ubuntu.com, pull requests merged in 2018-08, with the labels that each got.

#36 Update the webpage content
  package.json
  static/sass/_patterns_hero.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#38 Entrypoint for talisker gevent workers
  .gitignore
  Dockerfile
  entrypoint
  package.json
  requirements.txt
  run
Labels: Review: Code needed, Review: QA needed

#39 Add net-tools
  Dockerfile
Labels: Review: Code +1

#40 Update talisker entrypoint
  entrypoint
  requirements.txt
Labels: Review: Code +1
