Repository canonical/jp.ubuntu.com, pull requests merged in 2019-01, with the labels that each got.

#64 Update the navigation styling to match the new designs
  static/sass/_patterns_navigation.scss
  static/sass/_settings_colors.scss
  static/sass/_settings_general.scss
  static/sass/styles.scss
  templates/_base/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#65 51 ai ml
  static/sass/_settings_colors.scss
  static/sass/styles.scss
  templates/ai-ml.html
Labels: Review: Code +1, Review: Design +1, Review: UX +1

#67 Update the global-nav package to v1.2.1
  package.json
  templates/_base/footer.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#66 Enterprise support markup and contextual footer styling
  static/sass/_patterns_contextual-footer.scss
  static/sass/styles.scss
  templates/enterprise-support/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#73 Set Django to debug mode for development
  .env
Labels: Review: Code +1, Review: QA +1

#68 62 plans and pricing
  static/sass/_pattern_cloud-tools.scss
  static/sass/_pattern_contextual-footer.scss
  static/sass/_pattern_hero.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_pull-quotes.scss
  static/sass/_pattern_table.scss
  static/sass/styles.scss
  templates/enterprise-support/plans-and-pricing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#71 48 openstack
  static/sass/_pattern_pie-chart.scss
  static/sass/styles.scss
  templates/openstack.html
  templates/shared/_openstack-pie-chart.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#74 50 kubernetes
  templates/kubernetes.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#75 Built the /download page and added the feed parser
  requirements.txt
  templates/_further-reading-links.html
  templates/download.html
  webapp/settings.py
  webapp/templatetags/__init__.py
  webapp/templatetags/utils.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#79 56 iot page
  static/sass/_pattern_inline-images.scss
  static/sass/_settings_general.scss
  static/sass/styles.scss
  templates/_base/base.html
  templates/iot.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#72 Adds IOT page to jp.ubuntu.com
  templates/iot.html
Labels: Review: Code needed, Review: Design -1, Review: QA needed
