Repository canonical/jp.ubuntu.com, pull requests merged in 2019-07, with the labels that each got.

#157 [Takeover + Engage page] Yahoo (JP)
  templates/engage/yahoo.html
  templates/index.html
  webapp/blueprint.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#160 Update Yahoo engage page id and pdf link
  templates/engage/yahoo.html
Labels: Review: Code +1, Review: QA +1

#161 Update pricing on Kubernetes enterprise support packages
  templates/kubernetes.html
Labels: Review: Code +1, Review: QA +1

#162 Update enterprise support index page to match copy doc
  templates/enterprise-support/index.html
Labels: Review: Code +1, Review: QA +1

#165 Change the pdf for SBi
  templates/engage/sbi.html
Labels: Review: Code +1, Review: QA +1

#168 Adding takeover UTMs
  templates/takeovers/_sbi-takeover.html
  templates/takeovers/_yahoo-takeover.html
Labels: Review: Code +1, Review: QA +1

#166 Add social meta data
  templates/_base/base.html
  templates/blog/article.html
  templates/engage/openstack-made-easy.html
  templates/engage/sbi.html
  templates/engage/yahoo.html
Labels: Review: Code +1, Review: QA +1

#167 Add meta images to the Yahoo JP and SBI JP pages
  templates/engage/sbi.html
  templates/engage/yahoo.html
Labels: Review: Code needed, Review: QA needed
