Repository canonical/jp.ubuntu.com, pull requests merged in 2019-02, with the labels that each got.

#82 Added feed to footers, many clean-ups
  package.json
  redirects.json
  static/sass/_pattern_hero.scss
  templates/404.html
  templates/500.html
  templates/_base/base.html
  templates/_base/footer.html
  templates/ai-ml.html
  templates/contact-us.html
  templates/download.html
  templates/enterprise-support/index.html
  templates/enterprise-support/plans-and-pricing.html
  templates/index.html
  templates/iot.html
  templates/kubernetes.html
  templates/openstack.html
  templates/shared/_footer_feed.html
  templates/shared/_further-reading-links.html
  templates/shared/_openstack-pie-chart.html
  templates/shared/_thank-you.html
  templates/thank-you.html
  webapp/views.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#84 Added active state to menu based on the page you are on
  static/sass/_pattern_navigation.scss
  templates/_base/base.html
  webapp/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#89 Release new jp.ubuntu.com website
  .env
  package.json
  redirects.json
  requirements.txt
  static/sass/_pattern_cloud-tools.scss
  static/sass/_pattern_contextual-footer.scss
  static/sass/_pattern_hero.scss
  static/sass/_pattern_inline-images.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_pie-chart.scss
  static/sass/_pattern_pull-quotes.scss
  static/sass/_pattern_table.scss
  static/sass/_patterns_navigation.scss
  static/sass/_settings_colors.scss
  static/sass/_settings_general.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/_base/base.html
  templates/_base/footer.html
  templates/ai-ml.html
  templates/contact-us.html
  templates/download.html
  templates/enterprise-support/index.html
  templates/enterprise-support/plans-and-pricing.html
  templates/index.html
  templates/iot.html
  templates/kubernetes.html
  templates/openstack.html
  templates/shared/_contact-us-form.html
  templates/shared/_footer_feed.html
  templates/shared/_further-reading-links.html
  templates/shared/_openstack-pie-chart.html
  templates/shared/_thank-you.html
  templates/thank-you.html
  webapp/settings.py
  webapp/templatetags/__init__.py
  webapp/templatetags/utils.py
  webapp/views.py
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#90 Simple cloudinary test
  templates/_base/base.html
  templates/contact-us.html
  templates/index.html
  templates/shared/_openstack-pie-chart.html
  webapp/settings.py
Labels: Review: Code needed, Review: QA needed

#98 Bumped global-nav version to inline-svgs
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#100 Remove cloudinary from pdf url
  templates/openstack.html
Labels: Review: Code +1

#102 Migration to flask
  entrypoint
  package.json
  requirements.txt
  templates/404.html
  templates/500.html
  templates/_base/base.html
  templates/_base/footer.html
  templates/ai-ml.html
  templates/contact-us.html
  templates/download.html
  templates/enterprise-support/index.html
  templates/enterprise-support/plans-and-pricing.html
  templates/index.html
  templates/iot.html
  templates/kubernetes.html
  templates/openstack.html
  templates/shared/_footer_feed.html
  templates/shared/_further-reading-links.html
  templates/shared/_thank-you.html
  templates/thank-you.html
  tests/__init__.py
  tests/test_template_utils.py
  webapp/api.py
  webapp/app.py
  webapp/blueprint.py
  webapp/handlers.py
  webapp/template_utils.py
  webapp/wsgi.py
Labels: Review: Code +1, Review: QA +1

#107 Use right tags for Japan blog
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#108 Clean up stray Django files
  manage.py
  package.json
  webapp/settings.py
  webapp/urls.py
  webapp/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#110 Remove unused python dependencies
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#111 ReAdd talisker to the codebase
  .env
  entrypoint
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#112 Remove cssnano dep
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#113 Includes the blog card group styling, and aligns the titles horizontally
  requirements.txt
  static/sass/_utility_crop.scss
  static/sass/styles.scss
  templates/blog/blog-card.html
Labels: Review: Design +1

#114 Uncomment the blog route in the navigation bar
  templates/_base/base.html
  templates/blog/article.html
  templates/blog/index.html
Labels: Review: QA +1, Review: UX +1

#115 Use the translated title for blog
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1
