Repository canonical/jp.ubuntu.com, pull requests merged in 2019-04, with the labels that each got.

#125 Fix blog posts links in footers and feeds
  tests/test_template_utils.py
  webapp/template_utils.py
  webapp/templatetags/utils.py
Labels: Priority: High, Review: Code +1, Review: QA +1

#124 18.04.1 -> .2
  templates/download.html
Labels: Review: Code +1, Review: QA +1

#127 Don't crash when a blog post is missing some category/type metadata
  templates/blog/blog-card.html
Labels: Review: Code +1, Review: QA +1

#128 News on frontpage
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  package.json
  requirements.txt
  run
  static/js/global-nav.js
  static/js/latest-news.js
  static/js/lib/jquery-2.2.2.min.js
  templates/_base/footer.html
  templates/blog/blog-card.html
  templates/index.html
  templates/shared/_latest-news.html
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#129 Openstack Made Easy takeover
  redirects.json
  templates/engage/openstack-made-easy.html
  templates/engage/shared/_form.html
  templates/engage/shared/_header.html
  templates/index.html
  webapp/blueprint.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#134 Update /download to 19.04
  templates/download.html
Labels: Review: Code needed, Review: QA needed

#133 Removes dual id and unnecessary class
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1

#135 Added Google Optimize snippet
  templates/_base/base.html
Labels: Review: Code +1

#132 Loads the correct spotlight article
  requirements.txt
  static/js/latest-news.js
  templates/shared/_latest-news.html
Labels: Review: Code +1, Review: QA +1

#138 Updates blog module to 1.3.5 to fix 404 on article pages
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#139 Hide latest news until javascript is working
  static/js/latest-news.js
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
