Repository canonical/jp.ubuntu.com, pull requests merged in 2020-10, with the labels that each got.

#241 Fix blog tests
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1

#238 Build pepabo engage page
  templates/engage/case-study-gmo-pepabo.html
  templates/index.html
  webapp/blueprint.py
Labels: Review: Code +1, Review: QA +1

#242 Set width height to thumbnails
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#247 Update pepabo engage page
  templates/engage/case-study-gmo-pepabo.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#249 Add cookie-policy v3.0.3
  package.json
  static/js/cookie-policy.js
  static/sass/styles.scss
  templates/_base/footer.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#250 Move the manage link before report a bug
  templates/_base/footer.html
Labels: Review: Code +1

#253 Build GMO Pepabo takeover
  templates/index.html
  templates/takeovers/_gmo-pepabo-takeover.html
Labels: Review: Code +1, Review: Code needed, Review: QA +1, Review: QA needed

#260 20.10 release
  releases.yaml
  templates/download/index.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1
