Repository canonical/jp.ubuntu.com, pull requests merged in 2020-04, with the labels that each got.

#200 Initial commit of /download updates
  releases.yaml
  templates/download.html
Labels: Review: Code +1, Review: QA +1

#202 Add new /pricing page
  redirects.yaml
  templates/_base/base.html
  templates/_base/footer.html
  templates/ai-ml.html
  templates/download.html
  templates/engage/shared/_form.html
  templates/enterprise-support.html
  templates/enterprise-support/plans-and-pricing.html
  templates/iot.html
  templates/openstack.html
  templates/pricing.html
  templates/shared/_contact-us-form.html
  templates/shared/_further-reading-links.html
  webapp/blueprint.py
Labels: Review: Code +1, Review: QA +1

#203 Update to focal
  .circleci/config.yml
  Dockerfile
  entrypoint
  requirements.txt
  templates/_base/footer.html
  tests/test_template_utils.py
  webapp/app.py
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#204 Add secret_key to env file
  .env
Labels: Review: Code +1

#205 Update takeover template. Add 20.04 takeover
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/index.html
  templates/takeovers/_20.04.html
  templates/takeovers/shared/_template.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#206 Focal
  releases.yaml
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/download.html
  templates/index.html
  templates/takeovers/_20.04.html
  templates/takeovers/shared/_template.html
Labels: Review: Code +1, Review: QA +1

#208 Fix the title breaking
  templates/takeovers/_20.04.html
Labels: Review: Code needed, Review: QA needed
