Repository canonical/jp.ubuntu.com, pull requests merged in 2020-09, with the labels that each got.

#235 Create the CloudNative Days Tokyo 2020 page
  package.json
  static/sass/_settings_colors.scss
  templates/cloudnativedasytokyo2020.html
  tests/test_routes.py
  webapp/app.py
  webapp/blueprint.py
  yarn.lock
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#237 Update flask-base
  .github/workflows/pr.yaml
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#239 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1
