Repository canonical/jp.ubuntu.com, pull requests merged in 2024-08, with the labels that each got.

#485 WD-11655 - create /microcloud
  package.json
  templates/_base/navigation.html
  templates/microcloud.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#486 WD-11650 - refresh /iot
  static/sass/styles.scss
  templates/iot.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#487 WD-14011 - change footer microcloud link
  templates/_base/footer.html
Labels: Review: QA needed, Review: Code needed

#488 WD-13370 Bumped cookie-policy to v3.6.4
  package.json
  yarn.lock
Labels: Review: QA +1

#489 Refresh /pro
  redirects.yaml
  static/sass/styles.scss
  templates/_base/footer.html
  templates/_base/navigation.html
  templates/download/index.html
  templates/enterprise-support.html
  templates/index.html
  templates/kubernetes.html
  templates/openstack.html
  templates/pro.html
  templates/shared/_thank-you.html
  tests/test_routes.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#490 WD-11646 Refresh ai-ml page
  templates/ai-ml.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)
