Repository canonical/jp.ubuntu.com, pull requests merged in 2025-06, with the labels that each got.

#503 copy update: /download
  releases.yaml
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#504 Skip checking compressed CSS files content for LinkChecker
  .github/workflows/live-links.yml
Labels: Review: Code +1

#505 feat: Add calendly widget
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1
